# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from qgis.gui import QgsMapLayerComboBox

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_geocodingWindow(object):
    def setupUi(self, geocodingWindow):
        geocodingWindow.setObjectName(_fromUtf8("geocodingWindow"))
        geocodingWindow.resize(359, 612)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(geocodingWindow.sizePolicy().hasHeightForWidth())
        geocodingWindow.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.fileLineEdit = QtGui.QLineEdit(self.tab)
        self.fileLineEdit.setReadOnly(True)
        self.fileLineEdit.setObjectName(_fromUtf8("fileLineEdit"))
        self.horizontalLayout.addWidget(self.fileLineEdit)
        self.openFileButton = QtGui.QPushButton(self.tab)
        self.openFileButton.setObjectName(_fromUtf8("openFileButton"))
        self.horizontalLayout.addWidget(self.openFileButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.endPartesRadio = QtGui.QRadioButton(self.tab)
        self.endPartesRadio.setObjectName(_fromUtf8("endPartesRadio"))
        self.verticalLayout.addWidget(self.endPartesRadio)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.ruaComboBox = QtGui.QComboBox(self.tab)
        self.ruaComboBox.setObjectName(_fromUtf8("ruaComboBox"))
        self.horizontalLayout_6.addWidget(self.ruaComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.bairroComboBox = QtGui.QComboBox(self.tab)
        self.bairroComboBox.setObjectName(_fromUtf8("bairroComboBox"))
        self.horizontalLayout_5.addWidget(self.bairroComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.cidadeComboBox = QtGui.QComboBox(self.tab)
        self.cidadeComboBox.setObjectName(_fromUtf8("cidadeComboBox"))
        self.horizontalLayout_4.addWidget(self.cidadeComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.estadoComboBox = QtGui.QComboBox(self.tab)
        self.estadoComboBox.setObjectName(_fromUtf8("estadoComboBox"))
        self.horizontalLayout_3.addWidget(self.estadoComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.endUnicoRadio = QtGui.QRadioButton(self.tab)
        self.endUnicoRadio.setObjectName(_fromUtf8("endUnicoRadio"))
        self.verticalLayout.addWidget(self.endUnicoRadio)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.fullEndComboBox = QtGui.QComboBox(self.tab)
        self.fullEndComboBox.setObjectName(_fromUtf8("fullEndComboBox"))
        self.horizontalLayout_2.addWidget(self.fullEndComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setMinimumSize(QtCore.QSize(129, 0))
        self.label_8.setMaximumSize(QtCore.QSize(129, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.layersCombo = QgsMapLayerComboBox(self.tab_2)
        self.layersCombo.setObjectName(_fromUtf8("layersCombo"))
        self.horizontalLayout_7.addWidget(self.layersCombo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setMinimumSize(QtCore.QSize(129, 0))
        self.label_9.setMaximumSize(QtCore.QSize(129, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.horizontalLayout_8.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.dockWidgetContents)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.notfoundLineEdit = QtGui.QLineEdit(self.dockWidgetContents)
        self.notfoundLineEdit.setReadOnly(True)
        self.notfoundLineEdit.setObjectName(_fromUtf8("notfoundLineEdit"))
        self.horizontalLayout_9.addWidget(self.notfoundLineEdit)
        self.notfoundButton = QtGui.QPushButton(self.dockWidgetContents)
        self.notfoundButton.setObjectName(_fromUtf8("notfoundButton"))
        self.horizontalLayout_9.addWidget(self.notfoundButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.doGeocodeButton = QtGui.QPushButton(self.dockWidgetContents)
        self.doGeocodeButton.setObjectName(_fromUtf8("doGeocodeButton"))
        self.verticalLayout_2.addWidget(self.doGeocodeButton)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtGui.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_2.addWidget(self.lineEdit)
        geocodingWindow.setWidget(self.dockWidgetContents)

        self.retranslateUi(geocodingWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(geocodingWindow)

    def retranslateUi(self, geocodingWindow):
        geocodingWindow.setWindowTitle(_translate("geocodingWindow", "Geocodificação", None))
        self.label.setText(_translate("geocodingWindow", "Arquivo", None))
        self.openFileButton.setText(_translate("geocodingWindow", "Abrir...", None))
        self.endPartesRadio.setText(_translate("geocodingWindow", "Endereço fragmentado em campos", None))
        self.label_3.setText(_translate("geocodingWindow", "Logradouro", None))
        self.label_4.setText(_translate("geocodingWindow", "Bairro", None))
        self.label_5.setText(_translate("geocodingWindow", "Cidade", None))
        self.label_6.setText(_translate("geocodingWindow", "Estado", None))
        self.endUnicoRadio.setText(_translate("geocodingWindow", "Endereço em campo único", None))
        self.label_7.setText(_translate("geocodingWindow", "Endereço", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("geocodingWindow", "Direta", None))
        self.label_8.setText(_translate("geocodingWindow", "Camada de pontos", None))
        self.label_9.setText(_translate("geocodingWindow", "Novo atributo de endereço", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("geocodingWindow", "Reversa", None))
        self.label_10.setText(_translate("geocodingWindow", "Log de não encontrados", None))
        self.notfoundButton.setText(_translate("geocodingWindow", "Selecionar...", None))
        self.doGeocodeButton.setText(_translate("geocodingWindow", "Geocodificar", None))
        self.label_2.setText(_translate("geocodingWindow", "<html><head/><body><p>Google API key<br/>(Não tem uma? Clique <a href=\"http://bit.ly/dsgtoolsop-apikey\"><span style=\" text-decoration: underline; color:#0000ff;\">aqui</span></a>)</p></body></html>", None))
        self.lineEdit.setPlaceholderText(_translate("geocodingWindow", "Digite a API key", None))

