# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_import.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.gui import QgsProjectionSelectionWidget
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_importWindow(object):
    def setupUi(self, importWindow):
        importWindow.setObjectName(_fromUtf8("importWindow"))
        importWindow.resize(1037, 427)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(importWindow.sizePolicy().hasHeightForWidth())
        importWindow.setSizePolicy(sizePolicy)
        self.previewTable = QtGui.QTableWidget(importWindow)
        self.previewTable.setGeometry(QtCore.QRect(10, 156, 581, 261))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.previewTable.setFont(font)
        self.previewTable.setStyleSheet(_fromUtf8("font: 9pt \"Cantarell\";"))
        self.previewTable.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.previewTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectColumns)
        self.previewTable.setGridStyle(QtCore.Qt.DashLine)
        self.previewTable.setObjectName(_fromUtf8("previewTable"))
        self.previewTable.setColumnCount(0)
        self.previewTable.setRowCount(0)
        self.frame = QtGui.QFrame(importWindow)
        self.frame.setGeometry(QtCore.QRect(600, 10, 431, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(20, 6, 321, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ddRadio = QtGui.QRadioButton(self.groupBox)
        self.ddRadio.setGeometry(QtCore.QRect(10, 36, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ddRadio.setFont(font)
        self.ddRadio.setChecked(True)
        self.ddRadio.setObjectName(_fromUtf8("ddRadio"))
        self.milesimoRadio = QtGui.QRadioButton(self.groupBox)
        self.milesimoRadio.setGeometry(QtCore.QRect(10, 66, 109, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.milesimoRadio.setFont(font)
        self.milesimoRadio.setObjectName(_fromUtf8("milesimoRadio"))
        self.dmsRadio = QtGui.QRadioButton(self.groupBox)
        self.dmsRadio.setGeometry(QtCore.QRect(10, 96, 291, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dmsRadio.setFont(font)
        self.dmsRadio.setObjectName(_fromUtf8("dmsRadio"))
        self.label_4 = QtGui.QLabel(importWindow)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 561, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.createLayerButton = QtGui.QPushButton(importWindow)
        self.createLayerButton.setGeometry(QtCore.QRect(600, 350, 431, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.createLayerButton.setFont(font)
        self.createLayerButton.setObjectName(_fromUtf8("createLayerButton"))
        self.cancelButton = QtGui.QPushButton(importWindow)
        self.cancelButton.setGeometry(QtCore.QRect(600, 390, 431, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.label_5 = QtGui.QLabel(importWindow)
        self.label_5.setGeometry(QtCore.QRect(600, 204, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.layerNameEdit = QtGui.QLineEdit(importWindow)
        self.layerNameEdit.setGeometry(QtCore.QRect(760, 198, 271, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.layerNameEdit.setFont(font)
        self.layerNameEdit.setObjectName(_fromUtf8("layerNameEdit"))
        self.label_6 = QtGui.QLabel(importWindow)
        self.label_6.setGeometry(QtCore.QRect(600, 290, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.projectionWidget = QgsProjectionSelectionWidget(importWindow)
        self.projectionWidget.setGeometry(QtCore.QRect(760, 280, 271, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.projectionWidget.setFont(font)
        self.projectionWidget.setStyleSheet(_fromUtf8("font: 75 9pt \"Cantarell\";"))
        self.projectionWidget.setObjectName(_fromUtf8("projectionWidget"))
        self.label_7 = QtGui.QLabel(importWindow)
        self.label_7.setGeometry(QtCore.QRect(10, 17, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.filePathEdit = QtGui.QLineEdit(importWindow)
        self.filePathEdit.setGeometry(QtCore.QRect(110, 10, 441, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filePathEdit.setFont(font)
        self.filePathEdit.setReadOnly(True)
        self.filePathEdit.setObjectName(_fromUtf8("filePathEdit"))
        self.chooseFileButton = QtGui.QPushButton(importWindow)
        self.chooseFileButton.setGeometry(QtCore.QRect(560, 12, 31, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chooseFileButton.setFont(font)
        self.chooseFileButton.setObjectName(_fromUtf8("chooseFileButton"))
        self.label_8 = QtGui.QLabel(importWindow)
        self.label_8.setGeometry(QtCore.QRect(600, 164, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.decimalCombo = QtGui.QComboBox(importWindow)
        self.decimalCombo.setGeometry(QtCore.QRect(760, 160, 121, 28))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Cantarell"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.decimalCombo.setFont(font)
        self.decimalCombo.setStyleSheet(_fromUtf8("font: 75 9pt \"Cantarell\";"))
        self.decimalCombo.setObjectName(_fromUtf8("decimalCombo"))
        self.label_9 = QtGui.QLabel(importWindow)
        self.label_9.setGeometry(QtCore.QRect(10, 77, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.fpLongitudeEdit = QtGui.QLineEdit(importWindow)
        self.fpLongitudeEdit.setGeometry(QtCore.QRect(110, 70, 161, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fpLongitudeEdit.setFont(font)
        self.fpLongitudeEdit.setReadOnly(True)
        self.fpLongitudeEdit.setObjectName(_fromUtf8("fpLongitudeEdit"))
        self.label_10 = QtGui.QLabel(importWindow)
        self.label_10.setGeometry(QtCore.QRect(600, 244, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.layerTypeCombo = QtGui.QComboBox(importWindow)
        self.layerTypeCombo.setGeometry(QtCore.QRect(760, 240, 121, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.layerTypeCombo.setFont(font)
        self.layerTypeCombo.setObjectName(_fromUtf8("layerTypeCombo"))
        self.fpLatitudeEdit = QtGui.QLineEdit(importWindow)
        self.fpLatitudeEdit.setGeometry(QtCore.QRect(270, 70, 161, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fpLatitudeEdit.setFont(font)
        self.fpLatitudeEdit.setReadOnly(True)
        self.fpLatitudeEdit.setObjectName(_fromUtf8("fpLatitudeEdit"))
        self.label_11 = QtGui.QLabel(importWindow)
        self.label_11.setGeometry(QtCore.QRect(110, 100, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(importWindow)
        self.label_12.setGeometry(QtCore.QRect(270, 100, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.declinacaoEdit = QtGui.QLineEdit(importWindow)
        self.declinacaoEdit.setGeometry(QtCore.QRect(430, 70, 161, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.declinacaoEdit.setFont(font)
        self.declinacaoEdit.setReadOnly(True)
        self.declinacaoEdit.setObjectName(_fromUtf8("declinacaoEdit"))
        self.label_13 = QtGui.QLabel(importWindow)
        self.label_13.setGeometry(QtCore.QRect(430, 100, 161, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))

        self.retranslateUi(importWindow)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), importWindow.close)
        QtCore.QMetaObject.connectSlotsByName(importWindow)

    def retranslateUi(self, importWindow):
        importWindow.setWindowTitle(_translate("importWindow", "Azimutes e Distâncias", None))
        self.groupBox.setTitle(_translate("importWindow", "Unidade do azimute", None))
        self.ddRadio.setText(_translate("importWindow", "Grau decimal", None))
        self.milesimoRadio.setText(_translate("importWindow", "Milésimos", None))
        self.dmsRadio.setText(_translate("importWindow", "Grau, minuto e segundo (dd°mm°ss.sss\'\')", None))
        self.label_4.setText(_translate("importWindow", "Pré-visualização dos dados", None))
        self.createLayerButton.setText(_translate("importWindow", "Criar camada vetorial", None))
        self.cancelButton.setText(_translate("importWindow", "Cancelar", None))
        self.label_5.setText(_translate("importWindow", "Nome da nova camada", None))
        self.label_6.setText(_translate("importWindow", "SRC dos dados", None))
        self.label_7.setText(_translate("importWindow", "Arquivo CSV", None))
        self.chooseFileButton.setText(_translate("importWindow", "...", None))
        self.label_8.setText(_translate("importWindow", "Separador decimal", None))
        self.label_9.setText(_translate("importWindow", "Ponto inicial", None))
        self.label_10.setText(_translate("importWindow", "Tipo da camada", None))
        self.label_11.setText(_translate("importWindow", "Longitude", None))
        self.label_12.setText(_translate("importWindow", "Latitude", None))
        self.label_13.setText(_translate("importWindow", "Declinação", None))
